2022-05-11 03:20:01,180 INFO    MainThread:6248 [internal.py:wandb_internal():87] W&B internal server running at pid: 6248, started at: 2022-05-11 03:20:01.180570
2022-05-11 03:20:01,180 INFO    WriterThread:6248 [datastore.py:open_for_write():77] open: G:\Samei\Repo\RSNA-Bone-Age\wandb\offline-run-20220511_031959-kt3nonir\run-kt3nonir.wandb
2022-05-11 03:20:01,180 DEBUG   HandlerThread:6248 [handler.py:handle_request():130] handle_request: run_start
2022-05-11 03:20:01,321 DEBUG   HandlerThread:6248 [meta.py:__init__():40] meta init
2022-05-11 03:20:01,321 DEBUG   HandlerThread:6248 [meta.py:__init__():54] meta init done
2022-05-11 03:20:01,321 DEBUG   HandlerThread:6248 [meta.py:probe():214] probe
2022-05-11 03:20:01,337 DEBUG   HandlerThread:6248 [meta.py:_setup_git():204] setup git
2022-05-11 03:20:01,430 DEBUG   HandlerThread:6248 [meta.py:_setup_git():211] setup git done
2022-05-11 03:20:01,430 DEBUG   HandlerThread:6248 [meta.py:_save_pip():58] save pip
2022-05-11 03:20:01,430 DEBUG   HandlerThread:6248 [meta.py:_save_pip():72] save pip done
2022-05-11 03:20:01,430 DEBUG   HandlerThread:6248 [meta.py:_save_conda():79] save conda
2022-05-11 03:20:04,570 DEBUG   HandlerThread:6248 [meta.py:_save_conda():89] save conda done
2022-05-11 03:20:04,570 DEBUG   HandlerThread:6248 [meta.py:probe():252] probe done
2022-05-11 03:20:04,681 INFO    HandlerThread:6248 [handler.py:handle_tbrecord():640] handling tbrecord: tbrecord {
  log_dir: "tensorboard\\20220511_031959_MobileNetV2_Pre2"
  save: true
}

2022-05-11 03:20:04,681 DEBUG   HandlerThread:6248 [config_util.py:dict_from_config_file():102] no default config file found in config-defaults.yaml
2022-05-11 03:20:04,993 DEBUG   Thread-12 :6248 [tb_watcher.py:_process_events():269] Encountered tensorboard directory watcher error: [WinError 1314] A required privilege is not held by the client: 'G:\\Samei\\Repo\\RSNA-Bone-Age\\tensorboard\\20220511_031959_MobileNetV2_Pre2\\events.out.tfevents.1652264404.DESKTOP-ISIIVT7.264.0' -> 'G:\\Samei\\Repo\\RSNA-Bone-Age\\wandb\\offline-run-20220511_031959-kt3nonir\\files\\events.out.tfevents.1652264404.DESKTOP-ISIIVT7.264.0'
2022-05-11 03:30:33,819 WARNING MainThread:6248 [internal.py:is_dead():366] Internal process exiting, parent pid 264 disappeared
2022-05-11 03:30:33,819 ERROR   MainThread:6248 [internal.py:wandb_internal():142] Internal process shutdown.
2022-05-11 03:30:34,100 INFO    WriterThread:6248 [datastore.py:close():281] close: G:\Samei\Repo\RSNA-Bone-Age\wandb\offline-run-20220511_031959-kt3nonir\run-kt3nonir.wandb
2022-05-11 03:30:34,100 INFO    HandlerThread:6248 [handler.py:finish():731] shutting down handler
2022-05-11 03:30:34,834 INFO    SenderThread:6248 [sender.py:finish():1070] shutting down sender
2022-05-11 03:30:40,223 INFO    MainThread:6248 [internal.py:handle_exit():77] Internal process exited
